branches:
  only:
    - master
sudo: required
before_install:
- chmod +x ./build-script/gcloud-sdk-install.sh
install:
- "./build-script/gcloud-sdk-install.sh"
# script:
# - "./build-script/deploy-terraform.sh"
