branches:
  only:
    - master
sudo: required
before_install:
- chmod +x ./build-scripts/gcloud-sdk-install.sh
install:
- "./build-scripts/gcloud-sdk-install.sh"
# script:
# - "./build-scripts/deploy-terraform.sh"
