steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['config', 'current-context']
  volumes:
  - name: 'kube'
    path: '/kube'
  env:
  - 'KUBECONFIG=/kube/config'
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gcp-policy-management'
  - 'CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true'
- name: 'gcr.io/cloud-builders/git'
  args: [ 'clone', 'https://github.com/shaogang-google/grepo-e2e-0.git' ]
- name: 'ubuntu'
  args: [ '/workspace/bin/bespin', 'vet', '--path=/workspace' ]
  volumes:
  - name: 'kube'
    path: '/kube'
  env:
  - 'KUBECONFIG=/kube/config'
